= Требования к учетной записи Службы {ws}

_Служба {ws}_ является базовым модулем системы {dv}. Для учётной записи, от имени которой запускается служба *{wss}* требуются такие же права, как и для учётной записи модуля _{wf}_. Подробно требования перечислены ниже.

. Полный доступ к функциям администратора. Пользователь, от имени которого запускается _Служба {ws}_, должен состоять в группе локальных администраторов (*Administrators*) на сервере со _Службой {ws}_.
. _Служба {ws}_ считывает настройки из _{of-sett-serv}_, что требует соответствующих прав.
// +
// {sett-serv} хранит адрес _{of-mc}_. После изменения адреса _{of-mc}_ необходимо перезапустить IIS.
+
include::admin:launch.adoc[tags=console]
+
. Членство в группе *{dv-sys-wf-dir}*. Пользователь, от имени которого запускается _Служба {ws}_ должен состоять в группе *{dv-sys-wf-dir}* в справочнике сотрудников на сервере {dv}.
. Права на карточку сообщений очереди почтовых уведомлений. Пользователь, от имени которого запускается Служба {ws}, должен обладать правами на чтение, изменение и удаление карточки с идентификатором `0C052E58-3C25-4F29-8CE1-FF9CC2D1F31B`.
+
По умолчанию необходимые права выдаются автоматически при создании карточки сообщений. Если УЗ была изменена, соответствующие права на карточку необходимо выдать вручную.
