= Необходимые ресурсы

[#hard]
== Необходимое техническое обеспечение

Специальные требования не предъявляются.

[#soft]
== Необходимое программное обеспечение

* *Операционная система:* Microsoft Windows Server {serv-2} и выше.
* *Обязательное программное обеспечение:* Microsoft .NET Framework {net-v1}.

[#dv]
== Требования к системе {dv}

Модуль _Служба {ws}_ является обязательным для полноценной работы модулей {bo} и {ad}, см подробнее в пунктах xref:backoffice:admin:worker.adoc["Расширение службы {ws} для модуля {bo}"] и xref:backoffice:admin:worker.adoc["Расширение службы {ws} для модуля {ad}"].

[#account]
== Требования к учетной записи Службы {ws}

_Служба {ws}_ является базовым модулем системы {dv}. Для учётной записи, от имени которой запускается служба *{wss}* требуются такие же права, как и для учётной записи модуля _{wf}_. Подробно требования перечислены ниже.

. Полный доступ к функциям администратора. Пользователь, от имени которого запускается _Служба {ws}_, должен состоять в группе локальных администраторов (*Administrators*) на сервере со _Службой {ws}_.
. _Служба {ws}_ считывает настройки из _{of-sett-serv}_, что требует соответствующих прав.
+
include::admin:launch.adoc[tags=console]
+
. Членство в группе *{dv-sys-wf-dir}*. Пользователь, от имени которого запускается _Служба {ws}_ должен состоять в группе *{dv-sys-wf-dir}* в справочнике сотрудников на сервере {dv}.
