= Необходимые ресурсы

[#hard]
== Необходимое техническое обеспечение

Специальные требования не предъявляются.

[#soft]
== Необходимое программное обеспечение

* *Операционная система:* Microsoft Windows Server {serv-2} и выше.
* *Обязательное программное обеспечение:* Microsoft .NET Framework {net-v1}.

[#dv]
== Требования к системе {dv}

Модуль _Служба {ws}_ является обязательным для полноценной работы модулей {bo} и {ad}, см подробнее в пунктах xref:backoffice:admin:worker.adoc["Расширение службы {ws} для модуля {bo}"] и xref:backoffice:admin:worker.adoc["Расширение службы {ws} для модуля {ad}"].

[#account]
== Требования к учетной записи Службы {ws}

_Служба {ws}_ является базовым модулем системы {dv}. Для учётной записи, от имени которой запускается служба *{wss}* требуются такие же права, как и для учётной записи модуля _{wf}_. Подробно требования перечислены ниже.

. Членство в группе *Perfomance Monitor Users*.
. Полные права на системную папку для временных файлов (по умолчанию папка `c:\Windows\Temp`).
. Права на чтение веток реестра ОС:
+
* `{hklm-dv}\Platform`,
* `{hklm}\SYSTEM\CurrentControlSet\Services\EventLog\Security`.
+
. Права на редактирование веток реестра ОС:
+
* `{hklm}\SYSTEM\CurrentControlSet\Services\EventLog\Application`.
+
. Права в локальной политике безопасности:
+
* Log on as a service.
* Log on as a batch job.
* Adjust memory quotas for a process.
* Generate security audits.
* Replace а process level token.
* Impersonate a client after authentication.
* Allow log on locally.
* Access this computer from the network.
+
[NOTE]
====
Указанные разрешения выдаются в оснастке "Локальные политики безопасности" (menu:Control Panel[Administrative Tools > Local security policy > User Right Assigment].
====
+
. Полный доступ к функциям администратора. Пользователь, от имени которого запускается _Служба {ws}_, должен состоять в группе безопасности *{dv-admins-serv}* и группе локальных администраторов (*Administrators*) на сервере со _Службой {ws}_.
+
Данный пользователь также должен обладать правами на запись в файл журнала (если таковой ведется).
+
. Членство в группе *{dv-sys-wf-dir}*. Пользователь, от имени которого запускается _Служба {ws}_ должен состоять в группе *{dv-sys-wf-dir}* на сервере {dv}.
. Права на чтение списка типов установленных расширений:
+
Когда _Служба {ws}_ прочитает конфигурацию и создаст расширения, для работы отдельных расширений могут потребоваться права пользователей из группы _{dv-sys-wf-dir}_ в справочнике сотрудников {dv}.
+
. _Служба {ws}_ считывает настройки из _{of-sett-serv}_, что требует соответствующих прав.
+
include::admin:launch.adoc[tags=console]
