= Необходимые ресурсы

[#hard]
== Необходимое техническое обеспечение

Специальные требования не предъявляются.

[#soft]
== Необходимое программное обеспечение

* *Операционная система:* Microsoft Windows Server {serv-2} и выше.
// * *Обязательное программное обеспечение:* Microsoft .NET Framework {net-v1}.

[#dv]
== Требования к системе {dv}

Модуль _Служба {ws}_ является обязательным для полноценной работы модулей {bo} и {ad}, см подробнее в пунктах "xref:backoffice:admin:.worker.adoc[Расширение службы {ws} для модуля {bo}]" и "xref:backoffice:admin:.worker.adoc[Расширение службы {ws} для модуля {ad}]".

[#separate]
== Требования для установки на отдельную машину

Модуль Служба {ws} может устанавливаться на отдельную от сервера {dv} машину, см. "xref:admin:install.adoc[]". При этом к данной машине выдвигаются дополнительные требования.

.На отдельном сервере должны быть установлены серверные части следующих модулей:
* {pl} версии {pl-req} и выше.
* {ad} версии {ad-req} и выше.
* {bo} версии {bo-req} и выше.
* {dm} версии {dm-req} и выше.
* {wf} версии {wf-req} и выше.
