= Структура модуля

.Модуль включает в себя два компонента:
WorkerService.exe::
Исполняемый файл службы _{dv} 5.5 Worker Service_. Служба осуществляет запуск и контроль над порождаемыми рабочими процессами.
+
.Служба _{dv} 5.5 Worker Service_ реализует следующие функции:
* Загрузка конфигурации {ws} (_WorkerProcess_).
* Запуск требуемого количества {ws} с передачей им конфигурации.
* Контроль запущенности каждого рабочего процесса и перезапуск остановленных.
* Остановка {ws} при остановке службы.

WorkerProcess.exe и WorkerProcess32.exe::
Исполняемые файлы {ws} (x64 и x32-версии).
+
.Рабочий процесс (_WorkerProcess_) реализует следующие функции:
* Загрузка программных компонентов, указанных в полученной от _WorkerService_ конфигурации.
* Выполнение и контроль функций, реализованных в загруженных компонентах.

Загружаемые компоненты и необходимые для выполнения их функции настройки предоставляются устанавливаемыми расширениями для Службы {ws}. Расширения являются частью модулей {dv}, использующих Службу {ws}.
