= Структура модуля

Модуль включает в себя два компонента:

* WorkerService.exe – исполняемый файл службы «Docsvision 5.5 Worker Service», которая осуществляет запуск и контроль над порождаемыми рабочими процессами;
* WorkerProcess.exe и WorkerProcess32.exe – исполняемые файлы рабочих процессов (x64 и x32-версии).

Служба «Docsvision 5.5 Worker Service» реализует следующие функции:

* загрузка конфигурации рабочих процессов (WorkerProcess);
* запуск требуемого количества рабочих процессов с передачей им конфигурации;
* контроль запущенности каждого рабочего процесса и перезапуск остановленных;
* остановка рабочих процессов при остановке службы.

Рабочий процесс (WorkerProcess) реализует следующие функции:

* загрузка программных компонентов, указанных в полученной от WorkerService конфигурации;
* выполнение и контроль функций, реализованных в загруженных компонентах.

Загружаемые компоненты и необходимые для выполнения их функций настройки предоставляются устанавливаемыми расширениями для Службы рабочих процессов. Расширения являются частью модулей Docsvision, использующих «Службу рабочих процессов».