= Сервисы API

API Службы {ws} предоставляет сервисы, позволяющие получить доступ к различным функциям контекста выполнения _{of-ws}_.

Далее приведено описание функций предоставляемых сервисов. Инструкция по получению сервисов в коде расширений приведена в пункте xref:getServiceProvider.adoc[].

== IBasicConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IBasicConfigurationProvider` определяет функции провайдера к базовой конфигурации.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetBasicConfiguration()` -- возвращает экземпляр объекта `BasicConfiguration` (базовая конфигурация).
====

== IComponentConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IComponentConfigurationProvider` определяет функции провайдера к конфигурации _Компонентов_.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetConfiguration()` -- возвращает коллекцию объектов типа `ComponentTypeConfiguration` (конфигурация _Компонента_).
====

[#IConnectionPool]
== IConnectionPool

Интерфейс `{dv}.WorkerService.Interfaces.IConnectionPool` определяет методы пула подключений к внешним системам.

.Интерфейс определяет следующие методы:
[%collapsible]
====
* `GetConnection<T>()` -- возвращает _Подключение_ указанного типа. Строка соединения для создания подключения будет получена из первой по списку конфигурации данного _Подключения_.
* `GetConnection<T>(String)` -- возвращает _Подключение_ указанного типа. Строка соединения будет получена из конфигурации с названием `connectionName`.
* `GetConnection<T>(String, String)` -- возвращает подключение указанного типа. При создании подключения будет использована строка соединения `connectionSettings`.
* `ReleaseConnection<T>(T)` -- освобождает подключение указанного типа.
+
_Метод зарезервирован (не используется)_.
====

== IConnectionsConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IConnectionsConfigurationProvider` определяет функции провайдера к конфигурации _Подключений_.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetConfiguration()` -- возвращает коллекцию объектов типа `ConnectionTypeConfiguration` (конфигурация _Подключения_).
====

== IExtendedConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IExtendedConfigurationProvider` определяет функции провайдера к расширенной конфигурации.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetExtendedConfigurationServices()` -- возвращает коллекцию провайдеров к конфигурациям.
+
В стандартной реализации `GetExtendedConfigurationServices` возвращает провайдеры к конфигурациям Службы {ws}, _Компонентов_, _Подключений_, _Очереди сообщений_, _Ролей_, _Фабрики задач_.
====

== IQueuesConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IQueuesConfigurationProvider` определяет методы получения конфигурации _Очереди сообщений_.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetConfiguration()` -- возвращает коллекцию объектов типа `QueueTypeConfiguration` (конфигурация _Очереди сообщений_).
====

== IRolesConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IRolesConfigurationProvider` определяет методы получения конфигурации _Ролей_.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetConfiguration()` -- возвращает коллекцию объектов типа `RoleConfiguration` (конфигурация _Роли_).
====

== IWorkerProcessRuntimeConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IWorkerProcessRuntimeConfigurationProvider` определяет методы получения конфигурации {ws}.

.Интерфейс определяет следующие свойства:
[%collapsible]
====
* `Roles` -- должен возвращать список названий _Ролей_.
* `Components` -- должен возвращать список названий _Компонентов_.
* `Connections` -- должен возвращать список названий _Соединений_.
* `Queues` -- должен возвращать список названий _Очередей_.
* `Tasks` -- должен возвращать список названий _Фабрик задач_.
* `ShutdownTimeout` -- должен возвращать время ожидания завершения работы _Задач_ и _Компонентов_ при завершении работы {of-ws}.
+
По умолчанию -- одна минута.
====

== IWorkerServiceConfigurationManager

Интерфейс `{dv}.WorkerService.Interfaces.IWorkerServiceConfigurationManager` определяет методы работы с конфигурацией Службы {ws}.

.Интерфейс определяет следующие свойства:
[%collapsible]
====
* `ReadServiceConfiguration()` -- возвращает конфигурацию Службы.
* `SaveServiceConfiguration(WorkerServiceConfiguration)` -- сохраняет переданную конфигурацию Службы.
* `ReadProcessConfiguration(String)` -- возвращает конфигурацию _{of-ws}_.
* `SaveProcessConfiguration(WorkerProcessConfiguration)` --
_Метод зарезервирован (не используется)_.
====

== IWorkerTaskFactoriesConfigurationProvider

Интерфейс `{dv}.WorkerService.Interfaces.IWorkerTaskFactoriesConfigurationProvider` определяет методы получения конфигурации _Фабрики задач_.

.Интерфейс определяет единственный метод:
[%collapsible]
====
* `GetConfiguration()` -- возвращает коллекцию объектов типа `WorkerTaskFactoryTypeConfiguration` (конфигурация _Фабрики задач_).
====

== IWorkerTaskFactoryService

Интерфейс `{dv}.WorkerService.Interfaces.IWorkerTaskFactoryService` определяет метод получения _Фабрики задач_.

.Интерфейс определяет следующие методы:
[%collapsible]
====
* `RegisterFactory(IWorkerTaskFactory)` -- регистрирует переданную _Фабрику задач_ в собственном хранилище.
* `GetWorkerTaskFactory(IMessage)` -- возвращает _Фабрику задач_ поддерживающую создание _Задачи_ из сообщения типа `IMessage.TypeId`.
====

== IWorkerTaskQueue

Интерфейс `{dv}.WorkerService.Interfaces.IWorkerTaskQueue` определяет методы для работы с _Очередью задач_.

.Интерфейс определяет следующие методы и свойства:
[%collapsible]
====
* `Enqueue(IWorkerTask)` -- добавляет _Задачу_ в _Очередь задач_.
* `TryDequeue(out IWorkerTask)` -- удаляет и возвращает первую _Задачу_ из _Очереди задач_. Если метод выполнен успешно возвращает `*TRUE*`, иначе -- `*FALSE*`.
* `TryPeek(out IWorkerTask)` -- возвращает первую _Задачу_ из _Очереди задач_. Если метод выполнен успешно возвращает `*TRUE*`, иначе -- `*FALSE*`.
* `IsEmpty` -- возвращает `*TRUE*`, если _Очередь задач_ пуста.
* `NewItemInQueueSignal` -- предоставляет событие синхронизации потока. Ожидающий поток блокируется до добавления новой _Задачи_.
+
NOTE: Данный сервис нужно получать по названию класса реализации интерфейса, а не по названию интерфейса. Название класса реализации интерфейса: `WorkerTaskQueue`. См. пример в пункте xref:createTaskWithoutMessage.adoc[Создание Задачи без Сообщения].
====

== IProcessShutdownNotificator

Интерфейс `{dv}.WorkerService.Interfaces.IProcessShutdownNotificator` определяет методы сервиса остановки _{of-ws}_.

.Интерфейс определяет следующие методы и свойства:
[%collapsible]
====
* `Shutdown()` -- останавливает _фоновую операцию_, в которой выполняется текущая задача или компонент.
* `Signal` -- предоставляет событие синхронизации потока. Событие должно проверяться при реализации `Компонента`, не наследующего от `{dv}.WorkerService.Runtime.ThreadedRuntimeComponent`.
* `IsShuttingdown` -- возвращает статус остановки _{of-ws}_.
====
