= Разработка расширений Службы

_Расширение_ -- содержащий новые функции модуля дополнительный компонент, который может быть разработан программистом.

.Модуль поддерживает следующие типы расширений:
* _Компоненты_ -- предназначены для добавления любой функциональности, вызываемой при запуске {of-ws} и завершаемой при остановке {of-ws}. _Компоненты_ выполняются в отдельных потоках и через программные сервисы могут получать доступ к контексту работы {of-ws}.
* _Фабрики подключений_ -- предназначены для добавления собственных типов Подключений к внешним ресурсам.
* _Фабрики очереди сообщений_ -- предназначены для добавления собственных способов загрузки _Сообщений_.
* _Фабрики задач_ -- предназначены для добавления собственных способов формирования _Заданий_ из _Сообщений_.

Перечисленные типы расширений могут определять функции _Роли {of-ws}_.

Помимо данных основных типов расширений программист может реализовать собственные типы: провайдеров к расширенной конфигурации, _Сообщений_, _Задач_, _Подключений_ и пр. Примеры разработки и описание интерфейсов разрабатываемых дополнений приведены далее.

== Проект расширения

Расширение представляет собой .NET-сборку, в которой реализован класс (или классы) расширения.

.Чтобы разработать расширение:
. Создайте в Visual Studio проект типа `ClassLibrary`.
+
[IMPORTANT]
====
Версия платформы .NET Framework должна соответствовать версии, указанной в xref:ROOT:requirements.adoc[требованиях] Службы {ws}.

В проекте должна быть подпись для формирования сборки со строгим именем.
====
+
. Подключите к проекту сборку `{dv}.WorkerService.Interfaces.dll` (содержится в каталоге установки Службы {ws}: `C:\Program Files (x86)\Docsvision\WorkerService\5.5`).
+
. Добавьте в проект класс расширения требуемого типа:
+
* xref:.queueFactory.adoc[Фабрика очередей сообщений],
* xref:.taskFactory.adoc[Фабрика задач],
* xref:.connectionFactory.adoc[Фабрика подключений],
* xref:.сomponent.adoc[Компонент].
+
. Постройте проект.
