= Общие сведения о Службе {ws}

Модуль _Служба {ws}_ является дополнительным модулем {dv}, который реализует сервис асинхронного выполнения задач. Задачи могут создаваться Решением на платформе {dv} или другой системой.

.Возможности Службы:
Получение задач::
Служба может получать задачи из различных источников:
- Из базы данных.
- Из почты.
- Из файловой системы.
- Из прочих источников.

Параллельное выполнение задач::
Задачи могут выполняться последовательно или параллельно.

Изоляция процессов::
Задачи могут выполняться в выделенном физическом процессе.

Кластеризации::
Задачи могут выполняться несколькими экземплярами Службы {ws}.

Расширяемость::
Могут быть разработаны дополнительные компоненты, расширяющие возможности Службы {ws}.

== Состав Службы {ws}

.Служба включает исполняемые файлы:
* `WorkerService.exe` -- служба Windows, отвечающая за запуск, остановку и перезапуск остановившихся {ws}.
* `WorkerProcess.exe`/`WorkerProcess32.exe` -- исполняемые файлы _{of-ws}_ ({is-ws}) для архитектур x64/x86. {is-ws} выполняет полный цикл задач.

== Конфигурация

.Настройки Службы {ws} определяются в её конфигурации:
Базовая конфигурация::
Содержит общие настройки модуля:
+
--
- Путь к файлу журнала.
- Уровень протоколирования событий.
- Тип поставщика расширенной конфигурации.
--
+
NOTE: В стандартной реализации базовая конфигурация хранится в параметрах раздела `{hklm-dv}\WorkerService\5.5` реестра ОС.
+
Расширенная конфигурация::
Содержит настройки {ws}, настройки расширений (_Компонентов_, _Фабрик подключений_, _Фабрик очереди сообщений_, _Фабрик задач_), а также перечень и состав _Ролей_.
+
В стандартной реализации расширенная конфигурация хранится в подразделах `{hklm-dv}\WorkerService\5.5` реестра ОС:

WorkerProcesses:::
Содержит настройки экземпляров {of-ws}. Настройки экземпляра в собственном подразделе:

Architecture::::
Архитектура {of-ws}: `0` -- `AnyCpu`. Выполняется `WorkerProcess.exe`, `1` -- `x86` выполняется `WorkerProcess32.exe`, `2` -- `x64`.

Disabled::::
Отключает запуск данной {of-ws}, если в значении `1`.

Roles::::
Название _Ролей_ данной {of-ws}. Названия Ролей разделяются символом `;`.

Roles:::
Содержит описание _Ролей_. Описание каждой _Роли_ в отдельном разделе. В параметрах перечисляются типы расширений, используемых _Ролью_.

:en: Components
:case1: Компонент
:case2: Компонента
include::partial$chunks.adoc[]

:en: Connections
:case1: Фабрика подключений
:case2: Фабрики подключений
include::partial$chunks.adoc[]

:en: Queues
:case1: Фабрика очередей
:case2: Фабрики очередей
include::partial$chunks.adoc[]

:en: Tasks
:case1: Фабрика задач
:case2: Фабрики задач
include::partial$chunks.adoc[]
