= Общие сведения о Службе рабочих процессов

Модуль «Служба рабочих процессов» является дополнительным модулем Docsvision, который реализует сервис асинхронного выполнения задач. Задачи могут создаваться Решением на платформе Docsvision или другой системой.

Возможности Службы:

* получение задач из различных источников – служба может получать задачи из базы данных, почты, файловой системы и др.;
* параллельное выполнение задач;
* изоляция процессов – задачи могут выполняться в выделенном физическом процессе;
* кластеризации – задачи могут выполняться несколькими экземплярами Службы;
* расширяемость – могут быть разработаны дополнительные компоненты, расширяющие возможности Службы.

== Состав Службы

Служба рабочих процессов включает исполняемые файлы:

* `WorkerService.exe` – служба Windows, отвечающая за запуск, остановку и перезапуск остановившихся _Рабочих процессов_.
* `WorkerProcess.exe`/`WorkerProcess32.exe` – исполняемые файлы _Рабочего процесса_ для архитектур x64/x86. _Рабочий процесс_ (далее – РП) выполняет полный цикл задач.

== Конфигурация

Настройки Службы определяются в её конфигурации:

* Базовая конфигурация – содержит общие настройки Модуля: путь к файлу журнала, уровень протоколирования событий, тип поставщика расширенной конфигурации.

В стандартной реализации базовая конфигурация храниться в параметрах раздела `HKLM\SOFTWARE\DocsVision\WorkerService\5.5` реестра ОС.

* Расширенная конфигурация – содержит настройки _Рабочих процессов_, настройки расширений (*Компонентов*, _Фабрик подключений_, _Фабрик очереди сообщений_, _Фабрик задач_), а также перечень и состав _Ролей_.

В стандартной реализации расширенная конфигурация храниться в подразделах `HKLM\SOFTWARE\DocsVision\WorkerService\5.5` реестра ОС:

* «WorkerProcesses» – содержит настройки экземпляров РП (настройки экземпляра в собственном подразделе):

** «Architecture» – архитектура рабочего процесса: 0 – AnyCpu (выполняется «WorkerProcess.exe»), 1 – x86 (выполняется «WorkerProcess32.exe»), 2 – x64.
** «Disabled» – отключает запуск данного РП, если в значении «1».
** «Roles» – название Ролей данного РП. Названия Ролей разделяются символом «;».
* «Roles» – содержит описание Ролей (описание каждой Роли в отдельном разделе). В параметрах перечисляются типы расширений, используемых Ролью.

* «Components» – содержит описание расширений типа _Компонент_ (описание каждого _Компонента_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Компонент_ – в параметре «(По умолчанию)»;
** один или несколько параметров, содержащих настройки расширения данного типа.
* «Connections» – содержит описание расширений типа _Фабрика подключений_ (описание каждой _Фабрики подключений_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики подключений_ – в параметре «(По умолчанию)»;
** один или несколько параметров, содержащих настройки расширения данного типа.
* «Queues» – содержит описание расширений типа _Фабрика очередей_ (описание каждой _Фабрики очередей_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики очередей_ – в параметре «(По умолчанию)»;
** один или несколько параметров, содержащих настройки расширения данного типа.
* «Tasks» – содержит описание расширений типа _Фабрика задач_ (описание каждой _Фабрики задач_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики задач_ – в параметре «(По умолчанию)».