= Общие сведения о Службе рабочих процессов

Модуль "Служба {ws}" (далее -- Служба) является дополнительным модулем {dv}, который реализует сервис асинхронного выполнения задач, назначаемых другими модулями {dv} или сторонними системами.

Возможности Службы:

* Получение задач из различных источников. Задачи могут быть созданы и получены Службой из базы данных, почты, файловой система и пр. Также задачи могут быть созданы компонентами самой Службы.
* Параллельное выполнение задач.
* Изоляция процессов. Задачи определенного типа выполняются в выделенном физическом процессе.
* Устойчивость и гарантированность исполнения задач.
* Кластеризации. Задачи могут выполняться несколькими экземплярами Службы.
* Расширяемость. Программист может разработать дополнительные компоненты, расширяющие возможности Службы:
* работа с новыми источниками задач;
* подключение к внешним системам;
* новые способы создания задач.

= Объекты API

= Заготовка

В QueueManager (Менеджер очередей?):

. Из конфигурации получает IQueueFactory (queueFactory). Если несколько настроек, то вернёт несколько queueFactory.
. Из queueFactory получает IMessageGroupQueue (messageGroupQueue) и IMessageQueue (messageQueue).

Не нашел использования очередь сообщений (IMessageQueue) -- может не используется.

=== Как создаётся Задача по Сообщению

. Выбирается новое сообщение из группы сообщений IMessageGroup.
. Вызывается метод IWorkerTaskFactoryService.GetWorkerTaskFactory, в который передаётся Сообщение.
. GetWorkerTaskFactory выбирает первую фабрику задач, у которой MessageTypes содержит IMessage.TypeId
. Вызывается IWorkerTaskFactory.CreateWorkerTask

== Задача

Работа _Службы {ws}_ основана на выполнении Задач, которые могут создаваться внешними системами или внутренними процессами Службы.

Задачи могут быть созданы двумя способами:

* на основе Сообщений,
* непосредственно

_Задача_ является единица выполнения работы.

=== Пул соединений

Если задаче требуется подключаться к внешним ресурсам, вместо создания нового соединения можно использовать существующее соединение, которое можно получить из пула соединений.

Пул соединений -- объект типа `IConnectionPool`.

== Способы формирования задач

Для того, чтобы Служба выполнила какую-либо работу нужно создать _Задачу_. Это может быть сделано двумя способами:

* создать Сообщение, содержащее данные задачи;
* создание непосредственно задачу.

Задача является выполняемым объектом Службы.

=== Сообщение

_Сообщение_ -- пакет с данными, на основе которых формируется _Задача_. Исходные данные для формирования _Сообщения_ предоставляются внешней системой, которой требуется выполня

В стандартной реализации базовая конфигурация храниться в параметрах раздела `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС.

В стандартной реализации расширенная конфигурация храниться в подразделах `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС:

* "WorkerProcesses" -- содержит именованные группы (фактически -- разделы реестра) настроек РП. Каждая группа объединяет настройки одного РП, который должен запускаться службой "WorkerService":
* "Architecture" -- архитектура рабочего процесса: 0 -- AnyCpu (выполняется "WorkerProcess.exe"), 1 -- x86 (выполняется "WorkerProcess32.exe"), 2 -- x64.
* "Disabled" -- отключает запуск данного РП, если в значении "1".
* "Roles" -- название Ролей данного РП. Названия Ролей разделяются символом ";".
* "Roles" -- содержит описание Ролей (описание каждой Роли в отдельном разделе). В параметрах перечисляются типы расширений, используемых Ролью. Для каждого типа расширения может быть указано несколько экземпляров.
* "Components" -- содержит описание расширений типа _Компонент_ (описание каждого _Компонента_ содержится в отдельном разделе). В параметрах указывается:
* полное название класса _Компонент_ -- в параметре "(По умолчанию)";
* один или несколько параметров, содержащих настройки расширения данного типа. Название данных параметров указываются в списке расширений Роли.
* "Connections" -- содержит описание расширений типа _Фабрика подключений_ (описание каждой _Фабрики подключений_ содержится в отдельном разделе). В параметрах указывается:
* полное название класса _Фабрики подключений_ -- в параметре "(По умолчанию)";
* один или несколько параметров, содержащих настройки расширения данного типа. Название данных параметров указываются в списке расширений Роли.
* "Queues" -- содержит описание расширений типа _Фабрика очередей_ (описание каждой _Фабрики очередей_ содержится в отдельном разделе). В параметрах указывается:
* полное название класса _Фабрики очередей_ -- в параметре "(По умолчанию)";
* один или несколько параметров, содержащих настройки расширения данного типа. Название данных параметров указываются в списке расширений Роли.
* "Tasks" -- содержит описание расширений типа _Фабрика задач_ (описание каждой _Фабрики задач_ содержится в отдельном разделе). В параметрах указывается:
* полное название класса _Фабрики задач_ -- в параметре "(По умолчанию)";
* один или несколько параметров, содержащих настройки расширения данного типа. Название данных параметров указываются в списке расширений Роли.