= Типы расширений Службы

_Расширение_ – содержащий новые функции Модуля дополнительный компонент, который может быть разработан программистом. Модуль поддерживает следующие типы расширений:

* _Компоненты_ – предназначены для добавления любой функциональности, вызываемой при запуске РП и завершаемой при остановке РП. _Компоненты_ выполняются в отдельных потоках и могут получать доступ к контексту работы РП (через программные сервисы).
* _Фабрика подключений_ – предназначены для добавления собственных типов Подключений к внешним ресурсам.
* _Фабрика очереди сообщений_ – предназначены для добавления собственных способов загрузки _Сообщений_.
* _Фабрика задач_ – предназначены для добавления собственных способов формирования _Заданий_ из _Сообщений_.

Данные типы расширений могут определять функции _Роли рабочего процесса_.

Помимо данных основных типов расширений программист может реализовать собственные типы: провайдеров к расширенной конфигурации, _Сообщений_, _Задач_, _Подключений_ и пр. Примеры разработки и описание интерфейсов разрабатываемых дополнений приведены в данном документе.