= Жизненный цикл процессов Службы

Служба {ws} включает исполняемые файлы:

* `WorkerService.exe` -- служба Windows, задача которой запускать, останавливать и перезапускать остановившиеся _Рабочие процессы_.
* `WorkerProcess.exe` -- рабочий процесс в архитектуре x64;
* `WorkerProcess32.exe` -- рабочий процесс в архитектуре х86.

== Служба "WorkerService"

Жизненный цикл службы "WorkerService":

. При запуске `WorkerService.exe`:

. Загружает собственную конфигурацию и конфигурацию _Рабочих процессов_.

Базовая конфигурация -- содержит общие настройки Службы: путь к файлу журнала, уровень протоколирования событий, тип поставщика расширенной конфигурации.

. Инициализирует подсистему журналирования.

. Запускает подсистему _Менеджер {ws}_, который в соответствии с загруженной конфигурацией _Рабочих процессов_ запускает требуемое число экземпляров `WorkerProcess.exe` и `WorkerProcess32.exe` с передачей им имени конфигурации.
. В процессе работы `WorkerService` _Менеджер {ws}_ контролирует состояние каждого экземпляра рабочего процесса и, если он остановлен, -- запускает новый.

. При остановке службы "WorkerService" _Менеджер {ws}_ оповещает порожденные процессы об остановке и необходимости прекратить работу.

== Рабочий процесс (WorkerProcess)

Жизненный цикл службы РП:

. При запуске `WorkerProcess.exe`\`WorkerProcess32.exe`:

. Загружает базовую конфигурацию и создаёт провайдер расширенной конфигурации.

. Инициализирует подсистему журналирования.

. Инициализирует стандартные компоненты и сервисы, используемые при выполнении рабочего процесса.

. Загружает набор компонентов, предусмотренных конфигурацией.

. Запускает выполнение стандартных и подключаемых компонентов, реализующих интерфейс `IThreadedRuntimeComponent`, в отдельных потоках.

Все службы и проинициализированные компоненты помещаются в общий экземпляр `IServiceProvider`, который может быть передан во все компоненты рабочего процесса, поддерживающие интерфейс `IInitializeWithServiceProvider`.

. Рабочий процесс выполняет остановку при:

* получении сигнала об остановке от WorkerService;
* получении сигнала о необходимости остановки данного рабочего процесса;
* получении внутреннего сигнала о необходимости остановки от одного из загруженных компонентов.