= Описание процесса обработки сообщений

На следующей схеме представлен упрощенный процесс работы Службы {ws} и взаимодействия её компонентов. Зеленым обозначены расширения Службы, которые могут быть реализованы программистом.

.Обработка входящей корреспонденции
[plantuml, svg]
....
@startuml
'!pragma layout elk
skinparam rectangleBorderThickness 1
skinparam defaultTextAlignment center
skinparam lifelineStrategy solid

State "Внешние системы" as ext {

State "Система A" as sysA
State "Хранилище \nсобытий" as store
State "Система B" as sysB

}

State "Служба рабочих процессов" as serv {

State "Фабрика очередей" as queuesFactory #lightgreen
State "Очередь \nгрупп сообщений" as msgGroupQueue
msgGroupQueue : Сообщение 1 \nСообщение 2 \nСообщение N

State "Фабрика задач" as tasksFactory #lightgreen
State "Компонент" as comp #lightgreen

State "Фабрика \nподключений" as connectionsFactory #lightgreen
State "Подключение A" as conA

State "Менеджер задач" as mngr {

State "Задачи \nпо сообщениям" as msgTasks
State "Очередь задач" as tasksQueue

}

}

ext -[hidden]> serv
sysA --> store : Создание сообщения
store ---[hidden]> sysB
store -> msgGroupQueue : Загрузка\nсообщений
msgGroupQueue -u> tasksFactory : Обработка\nсообщений
msgGroupQueue -[hidden]d-> connectionsFactory

tasksFactory ---> msgTasks : Создание задач
queuesFactory --> msgGroupQueue : Инициализация
tasksFactory -[hidden]> comp
msgTasks : Задача 1\nЗадача 2 \nЗадача N
tasksQueue : Задача 1\nЗадача 2 \nЗадача N
comp --> tasksQueue : Создание задач

connectionsFactory ---> conA : Создание подключения
msgTasks -l> conA : Использование\nподключения

conA -> sysB : Подключение
@enduml
....

. Внешняя система создаёт сообщение в _Хранилище сообщений_.
+
При работе со Службой {ws} внешняя система создаёт задачи для Службы не напрямую, а через сообщения. В сообщениях содержатся данные, которых достаточно для создания задачи.
+
.Например, сообщение может содержать:
[%collapsible]
====
- Идентификатор объекта, над которым должна быть выполнена некоторая работа.
- Текст, который должен быть отправлен получателю и т. п.
====
+
Служба не предъявляет требований к формату таких сообщений и способу их хранения -- _Хранилище сообщений_.
+
Тип хранилища сообщений (например, база данных, система {dv}, файловая система), формат сообщений и способ добавления сообщений в хранилище выбираются программистом самостоятельно.
+
. _Фабрика очередей сообщений_ (`IQueueFactory`) создаёт экземпляр _Очереди групп сообщений_ (тип `IMessageGroupQueue`).
+
Сообщения могут иметь произвольный формат и храниться в произвольном _Хранилище сообщений_. Программист должен реализовать в _Очереди групп сообщений_ механизм получения сообщений из выбранного типа хранилищ.
+
Для получения _Очередей групп сообщений_ Служба обращается к зарегистрированным в настройках _Фабрикам очередей сообщений_, которые также реализуются программистом.
+
. _Очередь групп сообщений_ создаёт по сообщениям из _Хранилища сообщений_ объекты _Сообщение_ (тип `IMessage`).
+
В объект `IMessage` должны быть загружены данные исходного сообщения, которые нужны для выполнения соответствующей задачи в Службе {ws}, например: идентификатор объекта.
+
. _Фабрика задач_ преобразует загруженные _Сообщения_ (поступают в виде _Группы сообщений_) в _Задачи_ (`IWorkerTask`).
+
Непосредственно _Задачи_, которые должны быть выполнены Службой, формируются по поступившим _Сообщениям_ _Фабрикой сообщений_.
+
Каждая _Фабрика сообщений_ умеет создавать _Задачи_ по _Сообщениям_ определенного типа или типов. Тип _Сообщения_ указывается при его создании.
+
Программист должен реализовать _Фабрику сообщений_, которая умеет создавать _Задачи_ по разработанному программистом типу _Сообщений_.

. _Задачи_ также могут быть созданы расширением типа _Компонент_.
+
_Компонент_ -- вид расширения, функциональность не связана с обработкой _Сообщений_. Компонент запускается при старте РП, и останавливается -- при остановке РП.
+
Программист может реализовать в _Компоненте_ любые функции, соответствующие жизненному циклу _Компонента_.
+
. Сформированные двумя способами _Задачи_ выполняются _Менеджером задач_.
+
Если при выполнении _Задачи_ нужно подключаться к внешним системам (например, к почтовому серверу), можно использовать стандартные способы соединения -- _Подключения_. _Подключения_ создаются _Фабрикой подключений_.
+
Программист должен самостоятельно реализовать функцию создания _Подключения_ в _Фабрике подключений_.
+
TIP: _Подключение_ -- рекомендуемый способ получения соединения с внешней системой, но необязательный. Программист может создавать соединение непосредственно в _Задаче_.
