= Объекты

== Задача

_Задача_ является единицей работы Модуля. Выполнение _Задач_ является основным назначением Службы рабочих процессов.

_Задачи_ формируются _Фабрикой задач_ (`IWorkerTaskFactory`) из _Сообщений_ (`IMessage`), поступающих от внешних систем, а также могут быть сформированы напрямую в коде.

_Задача_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IWorkerTask`, который определяет единственный метод:

* `Work()` – содержит программный код, который должен быть выполнен для выполнения _Задачи_. Данный метод вызывается _менеджером задач_ (TaskManager, внутренний модуль Службы рабочих процессов) для выполнения соответствующей _Задачи_.

== Сообщение

_Сообщение_ является единицей информации, по которой в Модуле формируется _Задача_.

_Сообщения_ создаются внешней (по отношению к Модулю) системой. Способ хранения сообщений, их добавления и получения из хранилища определяется программистом. В роли хранилища могут выступать: таблица в БД, карточки в системе Docsvision, файлы на диске и др.

_Сообщение_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IMessage`, который определяет следующие свойства:

* `Id` – должен возвращать уникальный идентификатор _Сообщения_.
* `TypeId` – должен возвращать идентификатор типа _Сообщения_. Тип _Сообщения_ используется для получения «правильной» _Фабрики задач_.
* `SubTypeId` – должен возвращать идентификатор подтипа _Сообщения_. Подтип _Сообщения_ может использоваться в _Фабрике задач_ для принятия решения о варианте создания _Задачи_ по _Сообщению_.
* `TargetId` – должен возвращать идентификатор цели события. Может использоваться при создании _Задачи_. `TargetId` может, например, содержать идентификатор карточки, с которой выполняется работа в _Задаче_.
* `SourceId` – должен возвращать идентификатор источника _Сообщение_. В обычном случае можно возвращать идентификатор _Очереди сообщений_ (`IMessageGroupQueue.Id`). Идентификатор используется при протоколировании ошибок, возникающих при обработке _Сообщений_.
* `Data` – должен возвращать содержимое сообщение. Содержимое сообщение – любой объект, который потребуется для создания _Задачи_.

== Группа сообщений

Поступившие _Сообщения_ загружаются в обработчик Модуля скопом – _Группа сообщений_. _Сообщения_ одной группы разбираются последовательно в одном потоке. Разные _Группы сообщений_ обрабатываются в параллельных потоках, если есть свободные потоки.

_Группа сообщений_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IMessageGroup`, который определяет следующие свойства и методы:

* `Id` – должен возвращать уникальный идентификатор _Группы сообщений_.
* `SourceId` – должен возвращать идентификатор источника _Групп сообщений_. В обычном случае можно возвращать идентификатор _Очереди сообщений_ (`IMessageGroupQueue.Id`). Идентификатор используется при протоколировании ошибок, возникающих при обработке _Сообщений_.
* `Messages` – должен возвращать _Сообщения_ данной _Группы сообщений_.

== Очередь групп сообщений

_Очередь групп сообщений_ предоставляет доступ к необработанным _Группам сообщений_.

_Очередь групп сообщений_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IMessageGroupQueue`, который определяет следующие методы:

* `TryDequeue(out IMessageGroup)` – должен сохранить в `result` следующую _Группу сообщений_ с необработанными _Сообщениями_. Метод должен вернуть TRUE, если _Группа сообщений_ содержит сообщения, иначе – FALSE. Метод должен защитить _Сообщение_, добавляемое в _Группу сообщений_, от возможности добавления в другую _Группу сообщений_ (например, установить блокировку или флаг обработки) и при формировании группы добавлять только сообщения, которые не были добавлены в другую группу.

Т.к. _Группы сообщений_ могут обрабатываться параллельно, программисту важно организовать функцию `TryDequeue` (или способ получения _Сообщений_ из хранилища) таким образом, чтобы *исключить возможность повторной обработки* _Сообщений_.

* `TryPeek(out IMessageGroup)` – аналогично `TryDequeue`, но без блокировки _Сообщений_. Данный метод предназначен для проверки наличия необработанных _Сообщений_.

* Унаследованные методы интерфейса `IMessageGroupSource`.

== Фабрика очередей сообщений

_Фабрика очередей сообщений_ предоставляет методы получения _Очередей сообщений_.

_Фабрика очередей сообщений_ является одной из точек расширения Службы рабочих процессов. Данное расширение обеспечивает возможность получения (через _Очередь групп сообщений_) _Сообщений_ из хранилища, выбранного программистом.

_Фабрика очередей сообщений_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IQueueFactory`, который определяет единственный метод:

* `CreateQueue(String)` – должен вернуть _Очередь групп сообщений_ (`IMessageGroupQueue`).

Данный метод вызывается при запуске _Рабочего процесса_ Службы. В `settings` передаётся строка настроек, установленная для данной очереди в конфигурации, переданной _Рабочему процессу_. Если конфигурация содержит несколько настроек, метод `CreateQueue` будет вызван для каждой.

Класс, реализующий `IQueueFactory` также может реализовывать `IInitializeWithServiceProvider` для получения _поставщика сервисов_.

== Фабрика задач

_Фабрика задач_ предоставляет методы формирования _Задач_ по _Сообщениям_ .

_Фабрика задач_ является одной из точек расширения Службы рабочих процессов. Данное расширение обеспечивает возможность формирования _Задач_ с типом, который реализован программистом.

_Фабрика задач_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IWorkerTaskFactory`, который определяет следующие методы и свойства:

* `Id` – должен возвращать уникальной идентификатор _Фабрики задач_.

* `MessageTypes` – должен возвращать идентификаторы поддерживаемых типов _Сообщений_.

При обработке _Сообщения_ для создания _Задачи_ выбирается _Фабрика задач_, `MessageTypes` которой содержит идентификатор типа сообщения `IMessage.TypeId`.

* `CreateWorkerTask(IMessage)` – должен создавать _Задачу_ по переданному _Сообщению_.

* `CreateWorkerTask(IMessage, IWorkerTask)` – должен создавать _Задачу_ по переданному _Сообщению_. В `previousTask` будет передана последняя обработанная _Задача_.

== Фабрика подключений

_Фабрика подключений_ предоставляет подключение к внешнему ресурсу. Подключение может использоваться при получении _Сообщений_, при выполнении _Задач_, в работе _Компонентов_.

_Фабрика подключений_ является одной из точек расширения Службы рабочих процессов. Данное расширение обеспечивает стандартный способ получения подключения к внешнему ресурсу, разработанный программистом.

_Фабрика подключений_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IConnectionFactory`, который определяет следующие методы и свойства:

* `CreateConnection&lt;T&gt;(String)` – должен создавать и возвращать подключение с типом `T`. В `settings` передаётся строка подключения из конфигурации данного подключения.
* `SupportedTypes` – должен возвращать типы подключений, которые могут быть созданы методом `CreateConnection`.

== Компонент

_Компонент_ – реализуемый программистом дополнительный модуль Службы, который может содержать любую функциональность. Компонент не связан с циклом обработки _Сообщений_ и _Задач_; инициализируется при запуске _Рабочего процесса_ и останавливается при остановке процесса.

_Компонент_ является одной из точек расширения Службы рабочих процессов. Данное расширение обеспечивает возможность реализации программистом любой функциональности и возможностью получения xref:Services.adoc[сервисов API].

Служба может выполнять работы не только с помощью сообщений. Работа может выполняться _Компонентами_. Компоненты запускаются при старте рабочего процесса и останавливаются при его остановке.

_Фабрика подключений_ описывается программным интерфейсом `Docsvision.WorkerService.Interfaces.IThreadedRuntimeComponent`, который определяет следующие методы и свойства:

* `Start()` – должен запускать выполняемые функции _Компонента_. Данный метод будет единожды вызван при запуске _Рабочего процесса_.
* `Stop()` – должен останавливать выполняемые функции _Компонента_. Данный метод будет вызван при завершении и остановке работы _Рабочего процесса_.
* `Stopped` – должен вернуть текущее состояние работы _Компонента_: false – остановлен, true – запущен.

При реализации `Компонента` с наследованием от `IThreadedRuntimeComponent` необходимо обеспечить проверку поступления сигнала `IProcessShutdownNotificator.Signal` о завершении работы рабочего процесса. При этом работа компонента также должна быть завершена.

Компоненты должны реализовывать интерфейс `IThreadedRuntimeComponent` или (рекомендуется) наследоваться от класса `ThreadedRuntimeComponent`.

== IMessageGroupSource

Интерфейс `Docsvision.WorkerService.Interfaces.IMessageGroupSource` определяет методы обработки _Групп сообщений_.

Интерфейс определяет методы:

* `OnMessageGroupProcessingStart(IMessageGroup)` – должен обрабатывать событие запуска обработки _Группы сообщений_. Метод вызывается при отправке _Группы сообщений_ на обработку.
* `OnMessageGroupProcessingFinish(IMessageGroup)` – должен обрабатывать событие завершения обработки _Группы сообщений_. Метод вызывается после обработки всех сообщений _Группы сообщений_.
* Унаследованные методы интерфейса `IMessageSource`.

== IMessageQueue

Интерфейс `Docsvision.WorkerService.Interfaces.IMessageQueue` определяет методы получения _Сообщений_ из _Очереди сообщений_.

Интерфейс определяет методы:

* `TryDequeue(out IMessage)` – должен сохранить в `result` следующую необработанное _Сообщение_ из _Очереди сообщений_. Если есть необработанная _Группа сообщений_ метод должен вернуть TRUE, иначе FALSE. _Метод зарезервирован (не используется)_.
* `TryPeek(out IMessage)` – должен сохранить в `result` следующую необработанное _Сообщение_ из _Очереди сообщений_. Если есть необработанная _Группа сообщений_ метод должен вернуть TRUE, иначе FALSE. _Метод зарезервирован (не используется)_.
* Унаследованные методы интерфейса `IMessageSource`.

== IMessageSource

Интерфейс `Docsvision.WorkerService.Interfaces.IMessageSource` определяет методы обработки _Сообщений_.

Интерфейс определяет методы и свойства:

* `Id` – должен возвращать уникальный идентификатор данного источника сообщений.
* `OnMessageProcessingStart(IMessage)` – должен обрабатывать событие запуска обработки _Сообщения_. _Метод зарезервирован (не используется)_.
* `OnMessageProcessingFinish(IMessage, MessageState, Object)` – должен обрабатывать событие завершения обработки _Сообщения_. Метод вызывается после выполнения _Задания_, созданного по _Сообщению_ `message`. В `state` передаётся статус, с которым было обработано сообщение. В `details` передаётся содержание ошибки.

== IWorkerProcessManager

Интерфейс `Docsvision.WorkerService.Interfaces.IWorkerProcessManager` определяет методы _Менеджера процессов_.

Интерфейс определяет следующие метод, события и свойства:

* `Processes` – возвращает информацию о рабочих процессах.
* `StartProcess(String)` – запускает рабочий процесс с указанным именем.
* `StopProcess(String, Boolean)` – останавливает рабочий процесс с указанным именем. _Метод зарезервирован (не используется)_.
* `StartProcesses()` – запускает все рабочие процессы.
* `StopProcesses(Boolean)` – останавливает все рабочие процессы.
* `ProcessStarted` – событие запуска рабочего процесса.
* `ProcessStopped` – событие остановки рабочего процесса.

== ISettings

Интерфейс `Docsvision.WorkerService.Interfaces.IThreadedRuntimeComponent` определяет методы получения настроек _Компонента_.

Интерфейс определяет единственное свойство:

* `Data` – получает или возвращает строку настроек _Компонента_. Настройки сохраняются в `Data` перед вызовом метода `IThreadedRuntimeComponent.Start` класса _Компонента_.

== IInitializeWithServiceProvider

Интерфейс `Docsvision.WorkerService.Interfaces.IInitializeWithServiceProvider` определяет метод получения Поставщика сервисов.

Интерфейс определяет единственный метод:

* `Initialize(IServiceProvider)` – принимает поставщика сервисов.