= Общие сведения о Службе рабочих процессов

Модуль _Служба {ws}_ является дополнительным модулем {dv}, который реализует сервис асинхронного выполнения задач. Задачи могут создаваться Решением на платформе {dv} или другой системой.

.Возможности Службы:
Получение задач::
Служба может получать задачи из различных источников:
- Из базы данных.
- Из почты.
- Из файловой системы.
- Из прочих источников.

Параллельное выполнение задач::
Задачи могут выполняться последовательно или параллельно.

Изоляция процессов::
Задачи могут выполняться в выделенном физическом процессе.

Кластеризации::
Задачи могут выполняться несколькими экземплярами Службы {ws}.

Расширяемость::
Могут быть разработаны дополнительные компоненты, расширяющие возможности Службы {ws}.

== Состав Службы {ws}

.Служба включает исполняемые файлы:
* `WorkerService.exe` -- служба Windows, отвечающая за запуск, остановку и перезапуск остановившихся рабочих процессов.
* `WorkerProcess.exe`/`WorkerProcess32.exe` -- исполняемые файлы _Рабочего процесса_ (РП) для архитектур x64/x86. Рабочий процесс выполняет полный цикл задач.

== Конфигурация

.Настройки Службы {ws} определяются в её конфигурации:
Базовая конфигурация::
Содержит общие настройки модуля:
+
--
- Путь к файлу журнала.
- Уровень протоколирования событий.
- Тип поставщика расширенной конфигурации.
--
+
NOTE: В стандартной реализации базовая конфигурация хранится в параметрах раздела `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС.
+
Расширенная конфигурация::
Содержит настройки рабочих процессов, настройки расширений (_Компонентов_, _Фабрик подключений_, _Фабрик очереди сообщений_, _Фабрик задач_), а также перечень и состав _Ролей_.
+
В стандартной реализации расширенная конфигурация хранится в подразделах `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС:

WorkerProcesses:::
Содержит настройки экземпляров РП. Настройки экземпляра в собственном подразделе:

Architecture::::
Архитектура рабочего процесса: `0` -- `AnyCpu`. Выполняется `WorkerProcess.exe`, `1` -- `x86` выполняется `WorkerProcess32.exe`, `2` -- `x64`.

Disabled::::
Отключает запуск данного РП, если в значении `1`.

Roles::::
Название _Ролей_ данного РП. Названия Ролей разделяются символом `;`.

Roles:::
Содержит описание _Ролей_. Описание каждой _Роли_ в отдельном разделе. В параметрах перечисляются типы расширений, используемых _Ролью_.

:en: Components
:case1: Компонент
:case2: Компонента
ifndef::en[:en: Components]
ifndef::case1[:case1: Компонент]
ifndef::case2[:case2: Компонента]
include::partial$chunks.adoc[]

:en: Connections
:case1: Фабрика подключений
:case2: Фабрики подключений
ifndef::en[:en: Connections]
ifndef::case1[:case1: Фабрика подключений]
ifndef::case2[:case2: Фабрики подключений]
include::partial$chunks.adoc[]

:en: Queues
:case1: Фабрика очередей
:case2: Фабрики очередей
ifndef::en[:en: Queues]
ifndef::case1[:case1: Фабрика очередей]
ifndef::case2[:case2: Фабрики очередей]
include::partial$chunks.adoc[]

:en: Tasks
:case1: Фабрика задач
:case2: Фабрики задач
ifndef::en[:en: Tasks]
ifndef::case1[:case1: Фабрика задач]
ifndef::case2[:case2: Фабрики задач]
include::partial$chunks.adoc[]
