= Общие сведения о Службе рабочих процессов

Модуль _Служба {ws}_ является дополнительным модулем {dv}, который реализует сервис асинхронного выполнения задач. Задачи могут создаваться Решением на платформе {dv} или другой системой.

.Возможности Службы:
Получение задач::
Служба может получать задачи из различных источников:
- Из базы данных.
- Из почты.
- Из файловой системы.
- Из прочих источников.
Параллельное выполнение задач::
Задачи могут выполняться последовательно или параллельно.
Изоляция процессов::
Задачи могут выполняться в выделенном физическом процессе.
Кластеризации::
Задачи могут выполняться несколькими экземплярами Службы {ws}.
Расширяемость::
Могут быть разработаны дополнительные компоненты, расширяющие возможности Службы {ws}.

== Состав Службы {ws}

Служба включает исполняемые файлы:

* `WorkerService.exe` -- служба Windows, отвечающая за запуск, остановку и перезапуск остановившихся рабочих процессов.
* `WorkerProcess.exe`/`WorkerProcess32.exe` -- исполняемые файлы _Рабочего процесса_ для архитектур x64/x86. Рабочий процесс выполняет полный цикл задач.

== Конфигурация

.Настройки Службы определяются в её конфигурации:
Базовая конфигурация::
Содержит общие настройки модуля:
- Путь к файлу журнала.
- Уровень протоколирования событий.
- Тип поставщика расширенной конфигурации.

NOTE: В стандартной реализации базовая конфигурация хранится в параметрах раздела `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС.

Расширенная конфигурация::
Содержит настройки рабочих процессов, настройки расширений (_Компонентов_, _Фабрик подключений_, _Фабрик очереди сообщений_, _Фабрик задач_), а также перечень и состав _Ролей_.

NOTE: В стандартной реализации расширенная конфигурация хранится в подразделах `HKLM\SOFTWARE\{dv}\WorkerService\5.5` реестра ОС:

* WorkerProcesses -- содержит настройки экземпляров РП (настройки экземпляра в собственном подразделе):

** Architecture -- архитектура рабочего процесса: 0 -- AnyCpu (выполняется "WorkerProcess.exe"), 1 -- x86 (выполняется "WorkerProcess32.exe"), 2 -- x64.
** Disabled -- отключает запуск данного РП, если в значении "1".
** Roles -- название Ролей данного РП. Названия Ролей разделяются символом ";".
* Roles -- содержит описание Ролей (описание каждой Роли в отдельном разделе). В параметрах перечисляются типы расширений, используемых Ролью.

* Components -- содержит описание расширений типа _Компонент_ (описание каждого _Компонента_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Компонент_ -- в параметре "(По умолчанию)";
** один или несколько параметров, содержащих настройки расширения данного типа.
* Connections -- содержит описание расширений типа _Фабрика подключений_ (описание каждой _Фабрики подключений_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики подключений_ -- в параметре "(По умолчанию)";
** один или несколько параметров, содержащих настройки расширения данного типа.
* Queues -- содержит описание расширений типа _Фабрика очередей_ (описание каждой _Фабрики очередей_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики очередей_ -- в параметре "(По умолчанию)";
** один или несколько параметров, содержащих настройки расширения данного типа.
* Tasks -- содержит описание расширений типа _Фабрика задач_ (описание каждой _Фабрики задач_ содержится в отдельном разделе). В параметрах указывается:

** полное название класса _Фабрики задач_ -- в параметре "(По умолчанию)".