= Аннотация

== Назначение документа

Настоящий документ является руководством администратора модуля «Docsvision 5. Служба рабочих процессов» (далее – «Служба рабочих процессов», «Модуль»).

Документ содержит описание модуля и инструкцию по установке.

Документ предназначен для сотрудников, выполняющих установку Модуля.

== Как организован документ

Настоящее руководство содержит следующие разделы:

. link:GeneralInformation.md[Общие сведения] (приведены общие сведения о Службе рабочих процессов, перечислены требования к программному и аппаратному обеспечению компьютера для установки модуля).
. link:Structure.md[Структура модуля] (перечислены составные части Службы рабочих процессов).
. link:Installation.md[Установка и настройка] (содержит инструкцию по установке модуля).
. link:Administration.md[Функции администратора] (перечислены основные функции администратора модуля).

== Соглашения по оформлению

В данном документе для представления различных терминов и названий используются следующие шрифты и средства форматирования.

* *Жирный* – используется при написании названий элементов экранного интерфейса и выделения *важной информации*;
* _Курсив_ – используется для обозначения новых терминов, названий типов и видов карточек;
* http://docsvision.com[Синий] – используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц;
* `Моноширинный` – используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним.