= Установка Службы {ws}

:worker:

Пользователь, выполняющий установку Службы {ws}, должен обладать правами локального администратора.

// tag::sm-incompat[]
Служба {ws} данной версии несовместима с модулем {sm}.
// end::sm-incompat[]

.Особенности установки
****
При первичной установке модуль должен устанавливаться сразу после модуля _{pl}_ и перед модулями _{ad}_ и _{bo}_. В противном случае иначе необходимые расширения Службы {ws} не буду загружены в БД.

include::workerservice::partial$excerpts.adoc[tags=before-install]

include::ROOT:partial$excerpts.adoc[tags=the-component]
****

. Установите службу модуля следующей командой, предварительно обновив индекс пакетов:
+
[source,bash]
----
sudo apt-get update
sudo apt-get install docsvision-workerservice
----
+
. Все настройки модуля хранятся в конфигурационном файле модуля `Configuration.json`. Конфигурационный файл может быть изменён в любом текстовом редакторе, например `nano`.
+
[source,bash]
----
sudo nano /usr/lib/docsvision/workerservice/Configuration.json
----
+
Основные настройки, которые нужно сделать:
+
[source,json]
----
{
  "SettingsServiceConnectionString": "ConnectAddress=http://settings.domain.com:5200/api", <.>
  "ApiKey": "SettingsServiceApiKey", <.>
  "RestApiAddress": "http://worker.domain.com:5900/api", <.>
  "LogFile": "/tmp/WorkerService.log"
}
----
<.> Адрес Сервиса настроек.
<.> Ключ доступа к Сервису настроек (указывается в конфигурационном файле сервиса).
<.> Адрес Службы {ws}.
+
. Запустите службу модуля:
+
[source,bash]
----
sudo systemctl start dvworkerservice
----
