= Запуск Службы {ws}

Работу _Службы {ws}_ обеспечивает служба *{wss}*. Данная служба должна быть запущена от имени учётной записи с правами администратора, т.е. учётная запись должна быть добавлена в группу локальных администраторов на сервере {dv}.

_Cлужба {ws}_ может использовать сервис перештамповки подписей. Для корректной работы службы {ws} с использованием сервиса перештамповки подписей необходимо использовать машину, имеющую как минимум два процессора.

При первом запуске _Служба {ws}_ читает список типов установленных расширений и прописывает себя вместе с расширениями в _{sett-serv}_. Таким образом Служба {ws} идентифицирует себя и открывает доступ к своим функциям для системы {dv}.

В дальнейшем, когда _Служба {ws}_ прочитает конфигурацию и создаст расширения, для работы отдельных расширений могут потребоваться права пользователей из группы _{dv-sys-wf-dir}_ в справочнике сотрудников {dv}.

Все настройки службы считываются из _{of-sett-serv}_.

[NOTE]
====
// tag::console[]
При использовании модуля _{mc}_ убедитесь, что учётная запись, под которой запускается _Служба {ws}_ включена в группу *{dv-sett-serv-admins-serv}* на сервере с модулем _{mc}_.
// end::console[]
В противном случае будет недоступен xref:6.1@mgmtconsole:user:worker.adoc[узел Службы {ws}] в {of-mc}.
====
