= Запуск Службы {ws}

Работу Службы {ws} обеспечивает служба *{wss}*. Данная служба должна быть запущена от имени учётной записи с правами администратора, т.е. учётная запись должна быть добавлена в группу локальных администраторов на сервере {dv}.

Cлужба {ws} может использовать сервис перештамповки подписей. Для корректной работы службы {ws} с использованием сервиса перештамповки подписей необходимо использовать машину, имеющую как минимум два процессора.

При первом запуске Служба {ws} читает список типов установленных расширений и прописывает себя вместе с расширениями в _{sett-serv}_. Таким образом Служба {ws} идентифицирует себя и открывает доступ к своим функциям для системы {dv}.

В дальнейшем, когда Служба {ws} прочитает конфигурацию и создаст расширения, для работы этих отдельных расширений могут потребоваться права от группы _{dv-sys-wf-dir}_ в справочнике сотрудников {dv}.

Все настройки службы считываются из _{of-sett-serv}_.

NOTE: Если планируется использовать Службу {ws} вместе с модулем {mc}, необходимо, чтобы учётная запись, под которой запускается Служба {ws} была включена в группу *{dv-sett-serv-admins-serv}* на сервере {dv}. В противном случае будет недоступен xref:mgmtconsole:user:worker.adoc[узел Службы {ws}] в {of-mc}.
