= Параллельная обработка сообщений

В карточках сообщений может накапливаться очередь независимых сообщений, которые обрабатываются строго последовательно (например, отправка почтовых уведомлений). В таких случаях, несмотря на то, что сообщения не зависят друг от друга, может возникать задержка обработки. Работу с такими карточками ускоряет параллельная обработка сообщений, доступная в Службе {ws} версии {prl-msg-ws-cu} и выше.

[subs="specialchars,attributes,quotes"]
По умолчанию параллельная обработка отключена. Количество потоков обработки сообщений можно настроить в конфигурационном файле {config-ws}:

[source,json]
----
{
  "MaxConcurrentMessagesPerGroup": "1" <.>
}
----
<.> `MaxConcurrentMessagesPerGroup` -- максимальное количество сообщений из одной группы, обрабатываемых параллельно.

NOTE: Если параметр отсутствует в конфигурационном файле, создайте его самостоятельно.

Рекомендуется начинать с 5–10 потоков и регулировать значение в зависимости от ситуации и наличия ошибок с истемных журналах.