= Журнал работы

Журнал работы модуля в локальной файловой системе располагается по адресу: `C:\ProgramData\Docsvision\WorkerService\Logs`.

Учётная запись, под которой запущена Служба {ws}, должна обладать правами на запись в папку `C:\ProgramData\Docsvision\WorkerService\Logs`.

[NOTE]
====
Пути к журналам и уровень журналирования настраиваются в конфигурационном файле `C:\Program Files (x86)\Docsvision\WorkerService\5.5\Configuration.json` в параметрах:

* `LogFile` -- путь к журналу работы.
* `LogTraceLevel` -- уровень журналирования.
+
.Администратор может настроить следующие уровни журналирования:
** Журналирование отключено (Off) = `0`.
** Только ошибки (Error) = `1`.
** Ошибки и предупреждения (Warning) = `2`.
** Сообщения, ошибки и предупреждения (Info) = `3`. При установке данного уровня 1 раз в минуту в журнал будет записываться информация по текущей загрузке Службы {ws}: количество обработанных сообщений и задач, количество сообщений и задач в обработке.
** Подробное журналирование (Verbose) = `4`. При установке данного уровня в сообщениях о начале и завершении обработки сообщения указывается точный идентификатор сообщения (`RowID`) и идентификатор карточки сообщений (`InstanceID`). Также указывается точное время выполнения задач.
====
